services:
  minecraft-ftb:
    image: flobernd/minecraft-ftb:latest
    container_name: minecraft-ftb
    restart: unless-stopped
    tty: true
    stdin_open: true
    stop_grace_period: 1m
    environment:
      - "FTB_MODPACK_ID=126"
      - "ACCEPT_MOJANG_EULA=1"
    volumes:
      - ./volume:/var/lib/minecraft:rw
    ports:
      - 25565:25565
