name: CI

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        uses: reviewdog/action-hadolint@921946a7ebaaf08ac72607bad67209f4e52b5407 # v1.50.5
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'

  markdownlint:
    name: MarkdownLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # v0.26.2
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'

  yamllint:
    name: YamlLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'

  actionlint:
    name: ActionLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint
        uses: reviewdog/action-actionlint@0d952c597ef8459f634d7145b0b044a9699e5e43 # v1.71.0
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'
